# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'JieliJianKang' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JieliJianKang
  pod 'RxSwift','6.6.0'
  pod 'RxCocoa','6.6.0'
  pod 'SnapKit','5.6.0'
  pod 'Toast-Swift','5.0.1'
  pod 'Kingfisher','7.12.0'
  pod 'SwiftyAttributes','5.3.0'
  pod 'FMDB'

end
