#include "app_config.h"
[EXTRA_CFG_PARAM]
#if CONFIG_DOUBLE_BANK_ENABLE
BR22_TWS_DB = YES;	//dual bank flash framework enable
FLASH_SIZE = CONFIG_FLASH_SIZE;		//flash_size cfg
BR22_TWS_VERSION = 0; //default fw version
DB_UPDATE_DATA = YES; //generate db_update_data.bin
#else
NEW_FLASH_FS = YES;
#endif
CHIP_NAME = AD23N;
ENTRY = 0x8000100;
PID = AD23N;
VID = 0.01;
RESERVED_OPT = 0;
OTP_CFG_SIZE = 512;
CHECK_OTA_BIN = NO;
DOWNLOAD_MODEL = USB;
SERIAL_DEVICE_NAME = JlVirtualJtagSerial;
SERIAL_BARD_RATE = 1000000;
SERIAL_CMD_OPT = 2;
SERIAL_CMD_RATE = 100;
SERIAL_CMD_RES = 0;
SERIAL_INIT_BAUD_RATE = 9600;
LOADER_BAUD_RATE = 1000000;
LOADER_ASK_BAUD_RATE = 1000000;
BEFORE_LOADER_WAIT_TIME = 150;
SERIAL_SEND_KEY = YES;
SPECIAL_OPT = 0;
FORCE_4K_ALIGN = YES;
BOOT_HEAD_ALIGN = 3;
NEED_RESERVED_AREA = NO;
[BURNER_OPTIONS]
LONG_RESET_EN = YES;
SHORT_RESET_EN = YES;
[BURNER_PASSTHROUGH_CFG]
FLASH_WRITE_PROTECT = YES;
[CHIP_VERSION]
SUPPORTED_LIST = A;
[SYS_CFG_PARAM]
SPI = 2_3_0_0;
LRC = -1;
UTTX = PA05;
UTBD = 1000000;

[FW_ADDITIONAL]
FILE_LIST = (file = ota.bin: type = 100);

[RESERVED_CONFIG]
PRCT_ADR = 0;
PRCT_LEN = CODE_LEN;
PRCT_OPT = 2;

VM_ADR = 0;
VM_LEN = 32K;
VM_OPT = 1;

EEPROM_ADR = AUTO;
EEPROM_LEN = 24K;
EEPROM_OPT = 1;
[BURNER_CONFIG]
SIZE = 32;

